service: gaia-kickstart

plugins:
  - serverless-localstack
  - serverless-deployment-bucket

provider:
  name: aws
  region: ${self:custom.common.region}
  stackName: ${self:custom.stack_name}
  stage: ${self:custom.stage}
  cfnRole: arn:aws:iam::${self:custom.environment.aws_account_id}:role/GaiaAWSCloudFormationExecutionRole
  stackTags:
    ProjectName: Kickstart
  deploymentBucket: 
    name: ${self:service}-deployment-bucket

custom:
  stage: ${opt:env}
  stack_name: ${self:service}-${self:custom.stage}
  environment: ${file(../.env/env.yml):${self:custom.stage}}
  common: ${file(../shared/serverless-common.yml)}
  config:
    default: 
      deployments_bucket: ${self:custom.common.serverless_deployment_bucket}
  localstack:
    stages:
      - local
      - dev

resources:
  Resources:
    S3BucketServerlessDeployments:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.config.default.deployments_bucket}
        AccessControl: BucketOwnerFullControl
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256