service: gaia-politico

plugins:
  - serverless-localstack
  - serverless-deployment-bucket

provider:
  name: aws
  stackName: ${self:custom.stack_name}
  stage: ${self:custom.stage}
  region: ${self:custom.common.region}
  stackTags:
    ProjectName: Politico
  deploymentBucket:
    name: ${self:service}-deployment-bucket
  
custom:
  stage: ${opt:env}
  stack_name: ${self:service}-${self:custom.stage}
  environment: ${file(../.env/env.yml):${self:custom.stage}}
  common: ${file(../shared/serverless-common.yml)}
  localstack:
    stages:
      - local
      - dev
    
resources:
- ${file(./service-policies.yml)}
- ${file(./service-roles.yml)}